# Generated by Django 4.1 on 2022-08-31 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datefield',
            new_name='date_created',
        ),
    ]
